services:
  dashboard:
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    networks:
      - frontend-net
    volumes:
      - dashboard-prod:/mnt/dev/hammam/dashboard
    build: ./dashboard/.
    env_file:
      - prod.env
  gateway:
    ports:
      - ${GATEWAY_PORT}
    networks:
      - frontend-net
      - gateway-net
    build: ./gateway/.
    env_file:
      - prod.env
  database:
    image: mongo
    restart: always
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - database-prod:/mnt/dev/hammam/database
    networks:
      - database-net
    env_file:
      - prod.env
  anomaly-detector:
    env_file:
      - prod.env
    build: ./anomaly-detector/.
    ports:
      - ${DETECTOR_PORT}
    networks:
      - database-net

networks:
  frontend-net:
    driver: bridge
  database-net:
    driver: bridge
  gateway-net:
    driver: bridge

volumes:
  dashboard-prod:
  database-prod:
