services:

# Dashboard made in react
  dashboard:
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    volumes:
      - dashboard-dev:/mnt/dev/hammam/dashboard
    build: ./dashboard/.
    networks:
      - gateway

# RabbitMQ AMQP Broker
  rabbitmq:
    image: rabbitmq:4.0.7
    ports:
      - ${RABBIT_PORT}:${RABBIT_PORT}
    networks:
      - amqp-producers
      - amqp-consumers

# AMQP Client made in Java
  amqp-client:
    build: ./amqp-client/.
    ports:
      - ${AMQP_CLIENT_PORT}:${AMQP_CLIENT_PORT}
    networks:
      - amqp-consumers
      - amqp-anomalydetector
  
#MQTT Client made in Java
  mqtt-client:
    build: ./mqtt-client/.
    networks:
      - amqp-producers

# Gateway made in java spring
  gateway:
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    build: ./gateway/.
    networks:
      - gateway

# MongoDB database
  database:
    image: mongo
    restart: always
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - database-dev:/mnt/dev/hammam/database
    env_file:
      - .env
    networks:
      - database

# Anomaly detector made in express
  anomaly-detector:
    build: ./anomaly-detector/.
    ports:
      - ${DETECTOR_PORT}:${DETECTOR_PORT}
    networks:
      - amqp-anomalydetector
      - database

networks:
  amqp-producers:
  amqp-consumers:
  amqp-anomalydetector:
  database:
  gateway:

volumes:
  dashboard-dev:
  database-dev:
