services:

  # Dashboard made in react
  dashboard:
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    volumes:
      - dashboard-prod:/mnt/prod/hammam/dashboard
    build: ./dashboard/.
    networks:
      - gateway
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: false

  # RabbitMQ AMQP Broker
  rabbitmq:
    image: rabbitmq:4.0.7
    ports:
      - ${RABBIT_PORT}:${RABBIT_PORT}
    networks:
      - amqp-producers
      - amqp-consumers
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: false

  # AMQP Client made in Java
  amqp-client:
    build: ./amqp-client/.
    ports:
      - ${AMQP_CLIENT_PORT}:${AMQP_CLIENT_PORT}
    networks:
      - amqp-consumers
      - amqp-anomalydetector
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: false

  #MQTT Client made in Java
  mqtt-client:
    build: ./mqtt-client/.
    networks:
      - amqp-producers
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: false

  # Gateway made in java spring
  gateway:
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    build: ./gateway/.
    networks:
      - gateway
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: false

  # MongoDB database
  database:
    image: mongo
    restart: always
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - database-prod:/mnt/prod/hammam/database
    networks:
      - database
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: false

  # Anomaly detector made in express
  anomaly-detector:
    build: ./anomaly-detector/.
    ports:
      - ${DETECTOR_PORT}
    networks:
      - amqp-anomalydetector
      - database
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: false

networks:
  amqp-producers:
  amqp-consumers:
  amqp-anomalydetector:
  database:
  gateway:


volumes:
  dashboard-prod:
  database-prod: