services:

  # Dashboard made in react
  dashboard:
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    volumes:
      - dashboard-prod:/mnt/prod/hammam/dashboard
    build: ./dashboard/.
    networks:
      - gateway
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: true

  # Anomaly History Provider (Express)
  history-anomaly-rest:
    build: ./history-anomaly-provider/.
    ports:
      - ${HISTORY_ANOMALY_REST_PORT}
    networks:
      - database
      - history-anomaly-net
    env_file:
      - path: .env
        required: true
  
  # History provider (Express)
  history-rest:
    build: ./history-provider/.
    ports:
      - ${HISTORY_REST_PORT}
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: true
    networks:
      - database
      - history-net

  # RabbitMQ AMQP Broker
  rabbitmq:
    image: rabbitmq:4.0.7
    ports:
      - ${RABBIT_PORT}
    networks:
      - amqp-producers
      - amqp-consumers
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: true

  # AMQP Client made in Java
  amqp-client:
    build: ./amqp-client/.
    ports:
      - ${AMQP_CLIENT_PORT}
    networks:
      - amqp-consumers
      - amqp-anomalydetector
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: true

  #MQTT Client made in Java
  mqtt-client:
    build: ./mqtt-client/.
    networks:
      - amqp-producers
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: true

  # Gateway made in java spring
  gateway:
    ports:
      - ${GATEWAY_PORT}
    build: ./gateway/.
    networks:
      - gateway
      - history-anomaly-net
      - history-net
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: true

  # MongoDB database
  database:
    image: mongo
    restart: unless-stopped
    ports:
      - ${MONGODB_PORT}
    volumes:
      - database-prod:/mnt/prod/hammam/database
    networks:
      - database
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: true

  # Anomaly detector made in express
  anomaly-detector:
    build: ./anomaly-detector/.
    ports:
      - ${DETECTOR_PORT}
    networks:
      - amqp-anomalydetector
      - database
    env_file:
      - path: .env
        required: true
      - path: prod.env
        required: true

networks:
  amqp-producers:
  amqp-consumers:
  amqp-anomalydetector:
  database:
  gateway:
  history-anomaly-net:
  history-net:

volumes:
  dashboard-prod:
  database-prod: