services:

# Dashboard made in react
  dashboard:
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    build:
      context: ./dashboard/.
      dockerfile: dev.Dockerfile
    networks:
      - gateway-net
    env_file:
      - path: .env
        required: true
    depends_on:
      history-rest:
        condition: service_started
    volumes:
      - ./dashboard/app:/dashboard/app

  # Anomaly History Provider (Express)
  history-anomaly-rest:
    build: ./history-anomaly-provider/.
    ports:
      - ${HISTORY_ANOMALY_REST_PORT}:${HISTORY_ANOMALY_REST_PORT}
    networks:
      - database
      - history-anomaly-net
    env_file:
      - path: .env
        required: true
    depends_on:
      database:
        condition: service_healthy
  
  # History provider (Express)
  history-rest:
    build: ./history-provider/.
    ports:
      - ${HISTORY_REST_PORT}:${HISTORY_REST_PORT}
    env_file:
      - path: .env
        required: true
    networks:
      - database
      - history-net
    volumes:
      - ./history-provider:/node/dev
    depends_on:
      database:
        condition: service_healthy
  
#MQTT Client made in Java
  mqtt-client:
    build: ./mqtt-client/.
    networks:
      - mqtt-client-net
      - mqtt-broker-net
      - anomaly-detector-net
    env_file:
      - path: .env
        required: true
    depends_on:
      mqtt-broker:
        condition: service_started
    volumes:
      - ./mqtt-client:/building


#MQTT Broker with Eclipse Mosquitto
  mqtt-broker:
    networks:
      - mqtt-broker-net
    env_file:
      - path: .env
        required: true
    image: eclipse-mosquitto:latest
    volumes:
      - mqtt-data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
    ports:
      - 1883:1883


# Gateway Kong
  kong-migrations:
    image: kong/kong-gateway:3.9.1.0
    command: kong migrations bootstrap
    depends_on:
      kong-db:
        condition: service_healthy
    env_file: .env 
    networks:
      - gateway-net
    restart: on-failure

  gateway:
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    image: kong/kong-gateway:3.9.1.0
    networks:
      - gateway-net
      - history-anomaly-net
      - history-net
    env_file:
      - path: .env
        required: true
    depends_on:
      kong-migrations:
        condition: service_started

# Gateway DB
  kong-db:
    ports:
      - 5432:5432
    env_file: .env
    image: postgres:13
    restart: unless-stopped
    networks:
      - gateway-net
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "kong",
          "-U",
          "kong"
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - kong-data:/var/lib/postgresql/data

# MongoDB database
  database:
    image: mongo
    restart: unless-stopped
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      # - mongo-data:/data/db
      - ./mongo/config/:/docker-entrypoint-initdb.d/:rx
    networks:
      - database
    env_file:
      - path: .env
        required: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://${MONGO_READ_USER}:${MONGO_READ_PASSWORD}@localhost:${MONGODB_PORT}/${MONGO_INITDB_DATABASE} --quiet
      interval: 10s
      timeout: 10s
      retries: 5

# Anomaly detector made in express
  anomaly-detector:
    build: ./anomaly-detector/.
    ports:
      - ${DETECTOR_PORT}:${DETECTOR_PORT}
    networks:
      - anomaly-detector-net
      - database
    volumes:
      - ./anomaly-detector:/node/dev
    env_file: .env
    depends_on:
      database:
        condition: service_healthy

networks:
  mqtt-client-net:
  mqtt-broker-net:
  anomaly-detector-net:
  database:
  gateway-net:
  history-anomaly-net:
  history-net:

volumes:
  kong-data: {}
  mqtt-data: {}
  mongo-data: {}